version: "3.9"

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
    restart: always
